
create table "USER" ("ID" INTEGER NOT NULL,"NAME" VARCHAR NOT NULL,"ROLE" INTEGER NOT NULL);
create table "BUSINESS" ("ID" INTEGER NOT NULL,"NAME" VARCHAR NOT NULL, "DESC" VARCHAR NOT NULL, "DIVIDE_SYS" DOUBLE NOT NULL, "DIVIDE_INVEST" DOUBLE NOT NULL);
create table "INVEST" ("ID" BIGINT NOT NULL AUTO_INCREMENT, "USER_ID" INTEGER NOT NULL, "BUS_ID" INTEGER NOT NULL, "AMOUNT" INTEGER NOT NULL);

